# Define unit tests
py_test(
    name = "test_math_utils",
    srcs = ["tests/test_math_utils.py"],
    deps = [
        ":math_utils",
    ],
)
py_test(
    name="test_string_utils",
    srcs=["tests/test_string_utils.py"],
    deps=[":string_utils"],
)
