load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    urls = ["https://github.com/bazelbuild/rules_python/releases/download/0.29.0/rules_python-0.29.0.tar.gz"],
    strip_prefix = "rules_python-0.29.0",
    sha256 = "d71d2c67e0bce986e1c5a7731b4693226867c45bfe0b7c5e0067228a536fc580",
)

load("@rules_python//python:repositories.bzl", "python_register_toolchains")


python_register_toolchains(
    name = "python3",
    python_version = "3.10",  # Set your Python version
    python_path = "C:/Users/nurja/anaconda3/python.exe",  # Update this to match your Conda Python path
)

# Install pip dependencies
load("@rules_python//python:pip.bzl", "pip_install")

pip_install(
    name = "pip_deps",
    requirements = "//:requirements.txt",
)
