name: CI Pipeline of the Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Bazel
        uses: bazelbuild/setup-bazelisk@v2

      - name: Ensure Bazel Workspace Exists
        working-directory: python-bazel-ci/project-root
        run: |
          if [ ! -f WORKSPACE ] && [ ! -f MODULE.bazel.lock ]; then
            echo "ERROR: Bazel workspace not found in project-root!" >&2
            exit 1
          fi
        shell: bash

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        working-directory: python-bazel-ci/project-root
        run: |
          pip install pylint black pytest

      - name: Sync Bazel Dependencies
        working-directory: python-bazel-ci/project-root
        run: bazel sync --only=pip_deps

      - name: Run Unit Tests
        working-directory: python-bazel-ci/project-root
        run: bazel test //tests:test_math_utils //tests:test_string_utils

      - name: Run Black Formatter Check
        working-directory: python-bazel-ci/project-root
        run: black --check --exclude 'external|bazel-|third_party' .

      - name: Run Pylint
        working-directory: python-bazel-ci/project-root
        run: pylint tests src  

      - name: Run Formatter Check
        working-directory: python-bazel-ci/project-root
        run: |
          if bazel query //:format; then
            bazel test //:format
          else
            echo "Skipping //:format as it's not defined."
          fi

      - name: Run Linter Check
        working-directory: python-bazel-ci/project-root
        run: |
          if bazel query //:lint; then
            bazel test //:lint
          else
            echo "Skipping //:lint as it's not defined."
          fi
